### ISSUE TITLE
Default Gulp setup doesn't copy/serve the _data directory

### ISSUE THREAD

**Issue by emamd** [ireapps/first-graphics-app#11]
This would be solved by a fix to the gulp task in `copy.js`, but would change things from the default Yeogurt setup, I believe. Also having trouble dissecting that regex. 

The alternative is to request the data directly from the github repo, with the caveat that it could get super slow if the internet gets wonky.

**Comment by palewire** [comment]
Is this coming up as an issue because you want to make an AJAX call?

**Comment by emamd** [comment]
Yep. Though I just realized we could also use nunjucks to just include the data in the template? Think that's a good route?

**Comment by palewire** [comment]
If there's a filter or other easy way to dump the data file into the template as a JSON variable, I say do that. Could just print it as is?

**Comment by emamd** [comment]
That's probably the easiest way to go about it.
