### ISSUE TITLE
Should main.js come after the scripts block? 

### ISSUE THREAD

**Issue by emamd** [ireapps/first-graphics-app#13]
My thought is that we use the scripts block to write/include any data to the template, and then do all the charting/mapping/data manipulation inside of main.js. 

For example, 

```
{% block scripts %}
<script>
var homicides = {% include '_data/annual_totals.json' %}
</script>
{% endblock %}
```

and then inside of `charts.js` which is called from (or could be directly written into main.js) you can directly refer to the `homicides` variable which exists as a global on the template.

**Comment by palewire** [comment]
Let's talk this over tomorrow.

My only concern is that we're teaching a little bit of an anti-pattern if the main.js file, which is included on every page on the site, is extended to include JavaScript that should only ultimately appear on a single page.

I might be thinking about this wrong but here's what I'm itching to figure out: Can we put a slugged "harvard-park-homicides.js" file in the _scripts folder and have it compiled to be imported via a script tag in the nunjucks template alongside main.js? I fumbled around with this a little today but didn't find a way to make it click.

**Comment by emamd** [comment]
Yeah, maybe best to figure out on the phone, but it brings up two questions:

-  If we're building a single-page app, then shouldn't main.js relate as much as possible to that page?
- I've actually tripped up on this myself, if we're building a single page-app then maybe we should just be working off the root of the site instead of `/harvard-park-homicides/`

**Comment by palewire** [comment]
Yes it should. And I just switched it.
