### ISSUE TITLE
D4 chart setup steps

### ISSUE THREAD

**Issue by emamd** [ireapps/first-graphics-app#2]

**Comment by emamd** [comment]
Hmm apparently D4 hasn't been updated in nearly two years. This might not be the best approach, considering D3 itself has gone through major changes in that time.

**Comment by emamd** [comment]
Ok, doing a bit of research, it looks like there are some replacements that appear to be under active development we could use :
- [C3.js](https://github.com/c3js/c3)
- [d3plus](https://github.com/alexandersimoes/d3plus)
- [Plotly](https://plot.ly/javascript/bar-charts/)

Have y'all used any of these, @palewire @write-this-way? I've heard a bit about plotly and it's API seems simple for a basic bar chart, so leaning towards that but would like to hear your thoughts. We could also use vanilla D3 as well, I'm sure that would be fine. 

Also here's a nice list of [d3 things](https://github.com/wbkd/awesome-d3)

**Comment by palewire** [comment]
I'm open to just about anything. If the d3 route is too complicated, or chancy, we could always switch to other charting tools. Even something radically simpler like Chartbuilder could potentially work in my view.

**Comment by palewire** [comment]
There's also datawrapper.

**Comment by emamd** [comment]
#wontfix as we're switching to plotly
