### ISSUE TITLE
We could use an arrow function in the chart, but is it too much?

### ISSUE THREAD

**Issue by palewire** [ireapps/first-graphics-app#24]
I just pushed to change so you could consider it, @emamd.

```javascript
var countyHomicides = annualTotals.map(a => a.homicides_total);
var harvardParkHomicides = annualTotals.map(a => a.homicides_harvard_park);
var years = annualTotals.map(a => a.year);
```

**Comment by emamd** [comment]
I love arrow functions, but I worry that's a little level 2 javascript. On one hand it's really concise, on the other it's like "wait there's multiple ways to define functions?" 

Still... it's so concise and very nice in that format.

**Comment by emamd** [comment]
I've come around.
