### ISSUE TITLE
If our custom scss files start with an "_" should our JS ones also start with "_"?

### ISSUE THREAD

**Issue by palewire** [ireapps/first-graphics-app#43]

**Comment by emamd** [comment]
I don’t think it’s necessary. As far as I know it’s a convention with SASS but not w JS. 

Might not even be a convention with SASS just how I learned to do it 🤔

**Comment by palewire** [comment]
It seems a little weird to me that the JS files don't have it. I propose that we add it there as well. 

My read has always been that "_" prefix denotes that the file is "private" and will not ultimately be published to the live site (because it will be compiled into the main.js file.)

That private convention is generally followed elsewhere in Yeogurt with it's folder names. And it's common in other programming languages, like Python's private methods.

**Comment by palewire** [comment]
Sounds good to me. Let's also remember to point out the underscored folders at some points when we walk the students through the folders created by Yeogurt.
