### ISSUE TITLE
Don't think we need sudo on the npm commands

### ISSUE THREAD

**Issue by emamd** [ireapps/first-graphics-app#46]
```
sudo npm install -g yo gulp
sudo npm install -g generator-yeogurt
```

**Comment by emamd** [comment]
Windows doesn't have a sudo equivalent, aside from running command prompt "as administrator"
Node lets you install globally anyway, I believe

**Comment by palewire** [comment]
Good to know. I don't have a lot of confidence something like that is to be consistent across platforms and configurations.

We should probably have instructions ready for both cases. You will have sudo on Windows in some of the common terminal alternatives. We're going to need to decide which shell we have the students use in the lab.

**Comment by emamd** [comment]
I don't *think* npm needs `sudo` on mac either but I could be wrong. 

Meanwhile, just ran the install on plain ol' command prompt on a Windows 10 machine and it worked great!

**Comment by emamd** [comment]
there is also a git bash terminal the computers may have, depending on how git was installed, that might seem more familiar, since bash commands like `pwd` and `ls` will actually work. We'll have to check.

**Comment by palewire** [comment]
K. We can figure this stuff out the day before. I will also be in Wednesday and open most of the day. 

Great news about Windows! Thanks for doing that.

**Comment by palewire** [comment]
I just checked and all the sudos are gone. I think we can safely close this ticket.
