### ISSUE TITLE
Docs issue ... variable changes in example

### ISSUE THREAD

**Issue by critmcdonald** [ireapps/first-graphics-app#52]
There is a point in the docs when building charts that the `layout` variable changes to `chartLayout` in the example code:

```
var chartLayout = { //should be `layout`
    xaxis: {
        title: 'Year',
        fixedrange: true
    },
    yaxis: {
        fixedrange: true
    },
    // Add the margin here
    margin: {
        l: 45,
        r: 15,
        t: 45,
        b: 30
    },
    // Add a height parameter to the bottom of your file
    height: 250
};
```
If a student copy 'n' pastes the whole block, their variable will change and it won't work anymore.

**Comment by palewire** [comment]
We are deprecating this part of the class and replacing it with a different charting tool. The bug is legit, we're just nuking it.
