### ISSUE TITLE
Discrepancy between screenshot of yo yeogurt graphics app name and text instructions

### ISSUE THREAD

**Issue by emamd** [ireapps/first-graphics-app#72]
It's "First Graphics App" in the screenshot, and "first-graphics-app" in the instructions. I'd prefer the slug version, not sure it matters much.

**Comment by palewire** [comment]
Does the name get slotted into the title tag of the HTML base template? If so, I'd like to go with the humanized version over the slug. But I agree this isn't one we need to sweat too much. As long as we correct this to be consistent I'll be happy however we do it.

**Comment by emamd** [comment]
It doesn't because that is hard coded into the templat 
https://github.com/ireapps/first-graphics-app/blob/master/src/_layouts/base.nunjucks#L6

I vaguely remember the app not generating when I tried to use spaces in the title last year but haven't tried again. While I'm not sure where the app title is actually used, I think it'd be useful to emphasize slugging conventions, no spaces, no caps when naming things whenever possible.
