### ISSUE TITLE
Do we want people to overwrite their README.md at the end of yo yeogurt?

### ISSUE THREAD

**Issue by emamd** [ireapps/first-graphics-app#73]
I don't think it matters but assume people will get confused by an undocumented step.

**Comment by palewire** [comment]
Does this happen in cases where you are running the command on a blank directory?

**Comment by palewire** [comment]
I ask because if it only comes up when you "remake" the directory on top of an existing scaffold, I think we can skip documenting it since we won't be doing that in class.
